### ISSUE TITLE
Support migrators from ext

### ISSUE THREAD

**Issue by SuperKenVery** [Re4son/apt-btrfs-snapshot#1]
When migrating from ext, the root will not be on the `@` subvolume but `/`. Would you please consider removing the check of `"subvol=@" in entry.options`

I don't see any necessity to require `"subvol=@" in entry.options` to determine that it is the root fstab entry ---- as long as it's mounted as `/`, why not just take it?

**Comment by Re4son** [comment]
You're best to raise the issues with the Ubuntu team.
I've forked their repo to fork it for Kali Linux but never got to do it. Settled for snapper instead. This repo is dead.
